# Generated by Django 4.1.2 on 2022-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_session', models.CharField(max_length=32, null=True)),
                ('id_user', models.CharField(max_length=30, null=True)),
                ('file', models.FileField(upload_to='files')),
                ('path', models.CharField(max_length=512, null=True)),
                ('data', models.TextField(null=True)),
                ('id_reference', models.TextField(null=True)),
                ('data_analogs', models.TextField(null=True)),
                ('ids_analogs', models.TextField(null=True)),
                ('report', models.TextField(null=True)),
                ('NewData', models.TextField(null=True)),
                ('EndPool', models.FileField(null=True, upload_to='Export')),
            ],
        ),
        migrations.CreateModel(
            name='NumStreet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_street', models.IntegerField()),
                ('name_street', models.TextField()),
            ],
        ),
    ]
