# Generated by Django 4.1.2 on 2022-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='EndPool',
            field=models.TextField(null=True),
        ),
    ]
