# Generated by Django 4.1.2 on 2022-10-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='id_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
