# Generated by Django 4.1.2 on 2022-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0002_filedata_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='puth',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
