# Generated by Django 4.1.2 on 2022-10-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0003_filedata_puth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedata',
            old_name='puth',
            new_name='path',
        ),
    ]
