# Generated by Django 4.1.2 on 2022-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0005_filedata_id_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='id_session',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
