# Generated by Django 4.1.2 on 2022-10-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0006_alter_filedata_id_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
