# Generated by Django 4.1.2 on 2022-10-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0007_filedata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='id_reference',
            field=models.IntegerField(null=True),
        ),
    ]
