# Generated by Django 4.1.2 on 2022-10-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0008_filedata_id_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumStreet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_street', models.IntegerField()),
                ('name_street', models.TextField()),
            ],
        ),
    ]
