# Generated by Django 4.1.2 on 2022-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0009_numstreet'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='data_analogs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='filedata',
            name='ids_analogs',
            field=models.TextField(null=True),
        ),
    ]
