# Generated by Django 4.1.2 on 2022-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0010_filedata_data_analogs_filedata_ids_analogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='report',
            field=models.TextField(null=True),
        ),
    ]
