# Generated by Django 4.1.2 on 2022-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0011_filedata_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='id_reference',
            field=models.TextField(null=True),
        ),
    ]
